In [1]:
import os
import pandas as pd

# Folder path
folder_path = 'unsup'

# Initialize a list to store the data
data = []

# Loop through all files in the folder
for file in os.listdir(folder_path):
    # Check if the file is a text file
    if file.endswith('.txt'):
        file_path = os.path.join(folder_path, file)
        
        # Read the content of the file
        with open(file_path, 'r') as file:
            comments = file.readlines()
            
            # Add each line as a row in the data list
            for comment in comments:
                data.append({'Comment': comment.strip()})

# Create a DataFrame
df = pd.DataFrame(data)

df

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

                                                 Comment
0      A newspaperman (Johnny Twennies) living in the...
1      As co-founder of Nicko & Joe's Bad Film Club S...
2      Very good film from director Wyler, although i...
3      This flick will pass the time, and Kurt Russle...
4      The Feeding is a terrible werewolf movie about...
...                                                  ...
49995  I'll keep this short. <br /><br />Most of what...
49996  I absolutely love this show. I stumbled upon i...
49997  Ohh my God, I actually went out and bought thi...
49998  Angels and Insects is a thoughtful adult tale ...
49999  This is the greatest scripted, live action com...

[50000 rows x 1 columns]

In [9]:
sampled_df = df.sample(n=1400)

In [11]:
csv_file_path = '1400_cleaned.csv'
sampled_df.to_csv(csv_file_path, index=False)

## Manually Labeled Data (1 Category)

In [15]:
data_1cat = pd.read_csv('data_1cat.csv')
data_1cat

,Comment,Category 1
0,This is an unfortunate film. One of its bigges...,Directional Techniques
1,"Sometimes something sounds good, but the bare ...",Directional Techniques
2,A complete cult film in Spain.<br /><br />I th...,Directional Techniques
3,Some thoughts (for whatever they are worth)- <...,Directional Techniques
4,I saw that film when i studied films in englan...,Directional Techniques
...,...,...
1395,i have seen this film a few times but have nev...,Plot
1396,One of the earliest Japanese animation films I...,Visual Effect
1397,I found this movie an insult to the southern c...,Performance
1398,"Katrina (Emily Barcley) is a sad, pathetic, ut...",Plot
1399,I could not believe the good reviews that I sa...,Others

## Manually Labeled data (3 Category)

In [16]:
data_3cat = pd.read_csv('data_3cat.csv')
data_3cat

,Comment,Category 1,Category 2,Category 3
0,This is an unfortunate film. One of its bigges...,Directional Techniques,Visual Effect,NaN
1,"Sometimes something sounds good, but the bare ...",Directional Techniques,NaN,NaN
2,A complete cult film in Spain.<br /><br />I th...,Directional Techniques,NaN,NaN
3,Some thoughts (for whatever they are worth)- <...,Directional Techniques,NaN,NaN
4,I saw that film when i studied films in englan...,Directional Techniques,NaN,NaN
...,...,...,...,...
1395,i have seen this film a few times but have nev...,Plot,Performance,NaN
1396,One of the earliest Japanese animation films I...,Visual Effect,NaN,NaN
1397,I found this movie an insult to the southern c...,Performance,Visual Effect,NaN
1398,"Katrina (Emily Barcley) is a sad, pathetic, ut...",Plot,Performance,NaN
1399,I could not believe the good reviews that I sa...,Others,Directional Techniques,Plot